# Generated by Django 4.0 on 2022-01-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='spam',
            field=models.BooleanField(default=False),
        ),
    ]
