# Generated by Django 4.0 on 2022-01-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_spam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='spam',
            field=models.BooleanField(default=True),
        ),
    ]
